### ISSUE TITLE
Are we planning to have one CONTRIBUTING.md per language?

### ISSUE THREAD

**Issue by thanosbcc** [EAddario/java-master#2]
@EAddario  on the steps part of  the CONTRIBUTING.md page we provide the steps based on the java language. Are we planning to have a different CONTRIBUTING.md for each language (Python, Ruby, PHP, .Net, .js, Java)? If not, I think we should mention that this is an example for the case of java and that the same steps can be followed in a similar manner for the other languages.

**Comment by EAddario** [comment]
Yes
